import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'project.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'project.g.dart';

@freezed
abstract class Project with _$Project {
  const factory Project({
    required String id,
    required String collectionId,
    required String collectionName,
    required String created,
    required String updated,
    required String title,
    required String dateStart,
    required String dateEnd,
    required String gender,
    required String description_source,
    required String category,
    required String image,
    required String user_id,
  }) = _Project;

  factory Project.fromJson(Map<String, Object?> json) =>
      _$ProjectFromJson(json);
}
