import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:network/entity/project/project.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'responses_project.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'responses_project.g.dart';

@freezed
abstract class ResponsesProject with _$ResponsesProject {
  const factory ResponsesProject({
    required int page,
    required int perPage,
    required int totalPages,
    required int totalItems,
    required List<Project> items,
  }) = _ResponsesProject;

  factory ResponsesProject.fromJson(Map<String, Object?> json) =>
      _$ResponsesProjectFromJson(json);
}
