import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:network/entity/user/user.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'response_auth.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'response_auth.g.dart';

@freezed
abstract class ResponseAuth with _$ResponseAuth {
  const factory ResponseAuth({required User record, required String token}) =
      _ResponseAuth;

  factory ResponseAuth.fromJson(Map<String, Object?> json) =>
      _$ResponseAuthFromJson(json);
}
