import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:network/entity/user/user_auth.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'user_auth_list.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'user_auth_list.g.dart';

@freezed
abstract class UserAuthList with _$UserAuthList {
  const factory UserAuthList({
    required int page,
    required int perPage,
    required int totalPages,
    required int totalItems,
    required UserAuth items,
  }) = _UserAuthList;

  factory UserAuthList.fromJson(Map<String, Object?> json) =>
      _$UserAuthListFromJson(json);
}
