import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'user.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'user.g.dart';

@freezed
abstract class User with _$User {
  const factory User({
    required String collectionId,
    required String collectionName,
    required String created,
    String? email,
    required bool emailVisibility,
    required String firstname,
    required String id,
    required String lastname,
    required String secondname,
    required String updated,
    required bool verified,
    required String datebirthday,
    required String gender,
  }) = _User;

  factory User.fromJson(Map<String, Object?> json) => _$UserFromJson(json);
}
