import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'news.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'news.g.dart';

@freezed
abstract class News with _$News {
  const factory News({
    required String collectionId,
    required String collectionName,
    required String id,
    required bool newsImage,
    required String created,
    required String updated,
  }) = _News;

  factory News.fromJson(Map<String, Object?> json) => _$NewsFromJson(json);
}
