import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'product_item.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'product_item.g.dart';

@freezed
abstract class ProductItem with _$ProductItem {
  const factory ProductItem({
    required String id,
    required String title,
    required int price,
    required String typeCloses,
    required String type,
  }) = _ProductItem;

  factory ProductItem.fromJson(Map<String, Object?> json) =>
      _$ProductItemFromJson(json);
}
