import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:network/entity/shop/news.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'responses_news.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'responses_news.g.dart';

@freezed
abstract class ResponsesNews with _$ResponsesNews {
  const factory ResponsesNews({
    required int page,
    required int perPage,
    required int totalPages,
    required int totalItems,
    required List<News> items,
  }) = _ResponsesNews;

  factory ResponsesNews.fromJson(Map<String, Object?> json) =>
      _$ResponsesNewsFromJson(json);
}
