import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:network/entity/shop/product_item.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'response_products.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'response_products.g.dart';

@freezed
abstract class ResponseProducts with _$ResponseProducts {
  const factory ResponseProducts({
    required int page,
    required int perPage,
    required int totalPages,
    required int totalItems,
    required List<ProductItem> items,
  }) = _ResponseProducts;

  factory ResponseProducts.fromJson(Map<String, Object?> json) =>
      _$ResponseProductsFromJson(json);
}
