import 'package:freezed_annotation/freezed_annotation.dart';
import 'record.dart';
// required: associates our `main.dart` with the code generated by Freezed
part 'auth.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'auth.g.dart';

@freezed
abstract class Auth with _$Auth {
  const factory Auth({Record? record, String? token}) = _Auth;

  factory Auth.fromJson(Map<String, Object?> json) => _$AuthFromJson(json);
}
