import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'record.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'record.g.dart';

@freezed
abstract class Record with _$Record {
  const factory Record({
    String? collectionId,
    String? collectionName,
    String? created,
    String? firstName,
    bool? emailVisibility,
    String? firstname,
    String? id,
    String? lastname,
    String? secondname,
    String? updated,
    bool? verified,
    String? datebirthday,
    String? gender,
  }) = _Record;

  factory Record.fromJson(Map<String, Object?> json) => _$RecordFromJson(json);
}
