import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:network/entity/user.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'response_user.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'response_user.g.dart';

@freezed
abstract class ResponseUser with _$ResponseUser {
  const factory ResponseUser({required User? record, required String? token}) =
      _ResponseUser;

  factory ResponseUser.fromJson(Map<String, Object?> json) =>
      _$ResponseUserFromJson(json);
}
