import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:network/entity/user.dart';
import 'package:network/entity/user_auth.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'user_auth_paginator.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'user_auth_paginator.g.dart';

@freezed
abstract class UserAuthPaginator with _$UserAuthPaginator {
  const factory UserAuthPaginator({
    required int? page,
    required int? perPage,
    required int? totalPages,
    required int? totalItems,
    required UserAuth? items,
  }) = _UserAuthPaginator;

  factory UserAuthPaginator.fromJson(Map<String, Object?> json) =>
      _$UserAuthPaginatorFromJson(json);
}
