import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:network/entity/user.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'user_auth.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'user_auth.g.dart';

@freezed
abstract class UserAuth with _$UserAuth {
  const factory UserAuth({
    required String? id,
    required String? collectionId,
    required String? collectionName,
    required String? created,
    required String? updated,
    required String? collectionRef,
    required String? fingerprint,
    required String? recordRef,
  }) = _UserAuth;

  factory UserAuth.fromJson(Map<String, Object?> json) =>
      _$UserAuthFromJson(json);
}
