import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'response_order.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'response_order.g.dart';

@freezed
abstract class ResponseOrder with _$ResponseOrder {
  const factory ResponseOrder({
    required String id,
    required String collectionId,
    required String collectionName,
    required String created,
    required String updated,
    required String user_id,
    required String product_id,
    required int count,
  }) = _ResponseOrder;

  factory ResponseOrder.fromJson(Map<String, Object?> json) =>
      _$ResponseOrderFromJson(json);
}
